name: zenrouter_file_annotation
description: "Shared annotation and structure for zenrouter file generation and macros."
version: 0.2.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  meta: ^1.11.0
